apiVersion: v1
kind: Service
metadata:
  name: sem-redis-master
spec:
  ports:
    - port: 6379
      name: redis-port
      targetPort: 6379
    - port: 80
      name: web-port
      targetPort: 80
  type: NodePort
  selector:
    name: sem-redis-master


