---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  labels:
    product: "mysql"
  name: "mysql"
  namespace: "euler-system"
spec:
  deprecatedPublicIPs: []
  externalIPs: []
# modify ${clusterIP} by your environment
  clusterIP: 211.111.100.36
  ports:
  - port: 3306
# modify ${nodePort} by your environment
    nodePort: 33306
    targetPort: 3306
  selector:
    product: "mysql"
  type: "NodePort"