---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  labels:
    product: "euler-mkt"
  name: "euler-mkt"
  namespace: "euler-system"
spec:
  deprecatedPublicIPs: []
  externalIPs: []
# Modify ${clusterIP} by your environment
  clusterIP: 211.111.100.83
  ports:
  - port: 8080
# Modify ${nodePort} by your environment
    nodePort: 31083
    targetPort: 8080
  selector:
    product: "euler-mkt"
  type: "NodePort"