---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  labels:
    product: "euler-pfe"
  name: "euler-pfe"
  namespace: "euler-system"
spec:
  deprecatedPublicIPs: []
  externalIPs: []
# Modify ${clusterIP} by your environment
  clusterIP: 211.111.100.84
  ports:
  - port: 80
# Modify ${nodePort} by your environment
    nodePort: 31084
    targetPort: 80
  selector:
    product: "euler-pfe"
  type: "NodePort"