---
apiVersion: "v1"
kind: "ReplicationController"
# kind: "pod"
metadata:
  annotations: {}
  labels:
    product: "euler-pfe"
  name: "euler-pfe"
  namespace: "euler-system"
spec:
  replicas: 1
  selector:
    product: "euler-pfe"
  template:
    metadata:
      annotations: {}
      labels:
        product: "euler-pfe"
    spec:
      containers:
      - args: []
        image: "euler-registry.primeton.com/euler-pfe:0.2.0"
        imagePullPolicy: Always
        name: "euler-pfe"
        ports:
        - containerPort: 80
        env:
        - name: P_APP_ENV
# modify here by your environment
          value: "{'portalse_host':'', 'portalse_port':'', 'bpr_host':'', 'bpr_port':''}"
        resources:
          limits:
            cpu: "2000m"
            memory: "2Gi"
          requests:
            cpu: "200m"
            memory: "500m"
      imagePullSecrets: []
      nodeSelector: {}
