---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  labels:
    product: "euler-pm"
  name: "euler-pm"
  namespace: "euler-system"
spec:
  deprecatedPublicIPs: []
  externalIPs: []
# Modify ${clusterIP} by your environment
  clusterIP: 211.111.100.85
  ports:
  - port: 8080
# Modify ${nodePort} by your environment
    nodePort: 31085
    targetPort: 8080
  selector:
    product: "euler-pm"
  type: "NodePort"