---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  labels:
    product: "etcd1"
  name: "etcd1"
  namespace: "euler-system"
spec:
  deprecatedPublicIPs: []
  externalIPs: []
# modify ${clusterIP} by your environment
  clusterIP: 211.111.98.20
  ports:
  - name: port1
    port: 2379
# modify ${nodePort} by your environment
    nodePort: 33379
    targetPort: 2379
  - name: port2
    port: 2380
# modify ${nodePort} by your environment
    nodePort: 33380
    targetPort: 2380
  selector:
    product: "etcd1"
  type: "NodePort"