spring.profiles.include: msf

server:
    port: 8080

jdbc:    
    driver: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://211.111.100.36:3306/euler?autoReconnect=true&characterEncoding=UTF-8"
    user: "euler"
    password: "euler"
    maxPoolSize: 20

jenkins:
    clients:
       - name: "clientA"
         url: "http://10.217.4.32:8080/"
         user: "admin"
         password: "admin"

bpr:
    url: "http://10.217.4.32:8081/"
    user: "admin"
    password: "admin123"
        
dpr:
    url: "euler-registry.primeton.com"
    user: ""
    password: ""
    
application:
    name: ci
    initialBuildEstimatedDuration: 90000
    initialBuildNumber: 1000
    buildCountLimit: 10
    buildDaysLimit: 5

# application server ip port
service:
  registries:
   - name: iam
     domain: "211.111.100.82:8080"
    
srd:
  group: euler_group
  regProtocol: etcd
  addresses:
  - 10.217.4.47:32379
          
token:
    validate:
        remote: true
        excludeUrl: "/ci/jobs/jobBuildDetails"
