spring.profiles.include: msf

server:
    port: 8080

pm:
    db:
        url: jdbc:mysql://211.111.100.36:3306/euler?autoReconnect=true&characterEncoding=UTF-8
        user: euler
        password: euler
        type: com.mchange.v2.c3p0.ComboPooledDataSource
        driverClass: com.mysql.jdbc.Driver
        maxPoolSize: 20

#application name
application:
  name: pm

# application server ip port
service:
  registries:
   - name: iam
     domain: "211.111.100.82:8080"

srd:
  group: euler_group
  regProtocol: etcd
  addresses:
    - 10.217.4.47:32379
    
token:
  validate:
    remote: true
